# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build with Nodejs
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    - run: npm run build

    - name: Deploy JoiAsk-frontend
      uses: horochx/deploy-via-scp@1.1.0
      with:
        host: ask.vjoi.cn
        port: 22
        key: ${{ secrets.DEPLOY_KEY }}
        remote: /var/www/html/ask/
        local: ${{ github.workspace }}/public
